# TheRxSpot Marketplace Launch Script
$ErrorActionPreference = 'Stop'

Write-Host '
===================================================' -ForegroundColor Cyan
Write-Host '   TheRxSpot Marketplace | Service Orchestrator' -ForegroundColor Cyan
Write-Host '===================================================
' -ForegroundColor Cyan

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot ".")).Path
$storefrontRoot = Join-Path $repoRoot "TheRxSpot_Marketplace-storefront"
$launcherHtml = Join-Path $repoRoot "Marketplace-Launcher.html"
$preferredBackendPort = 9000
$fallbackBackendPort = 9001
$backendPort = $preferredBackendPort
$preferredStorefrontPort = 8000
$fallbackStorefrontPort = 8001
$storefrontPort = $preferredStorefrontPort
$adminUiPort = 5173

function Get-AdminPathFromConfig {
    param([string]$RepoRoot)

    $configPath = Join-Path $RepoRoot "medusa-config.ts"
    if (-not (Test-Path $configPath)) {
        return "/app"
    }

    $content = Get-Content $configPath -Raw
    if ($content -match 'path:\s*"([^"]+)"') {
        $path = $matches[1].Trim()
        if (-not $path.StartsWith("/")) {
            $path = "/$path"
        }
        if ($path.Length -gt 1 -and $path.EndsWith("/")) {
            $path = $path.TrimEnd("/")
        }
        return $path
    }

    return "/app"
}

function Update-LauncherRuntimeConfig {
    param(
        [string]$RepoRoot,
        [int]$BackendPort,
        [int]$StorefrontPort,
        [string]$AdminPath
    )

    $normalizedAdminPath = if ([string]::IsNullOrWhiteSpace($AdminPath)) { "/app" } else { $AdminPath.Trim() }
    if (-not $normalizedAdminPath.StartsWith("/")) {
        $normalizedAdminPath = "/$normalizedAdminPath"
    }
    if ($normalizedAdminPath.Length -gt 1 -and $normalizedAdminPath.EndsWith("/")) {
        $normalizedAdminPath = $normalizedAdminPath.TrimEnd("/")
    }

    $runtimeConfigContent = @"
// Auto-generated by Launch-Marketplace.ps1
window.__THERXSPOT_LAUNCHER_PORTS = {
  backendPort: $BackendPort,
  storefrontPort: $StorefrontPort,
  adminPath: "$normalizedAdminPath",
  generatedAt: "$(Get-Date -Format "yyyy-MM-ddTHH:mm:ss")"
};
"@

    Set-Content -Path (Join-Path $RepoRoot "launcher_assets\runtime-config.js") -Value $runtimeConfigContent -Encoding utf8
}

# Step 0: Check Dependencies
Write-Host '[0/5] Checking dependencies...' -ForegroundColor Yellow

# Fast port check function (Test-NetConnection is too slow)
function Test-Port {
    param($Port)
    try {
        $tcpClient = New-Object System.Net.Sockets.TcpClient
        $tcpClient.ReceiveTimeout = 1000
        $tcpClient.SendTimeout = 1000
        $result = $tcpClient.BeginConnect("127.0.0.1", $Port, $null, $null)
        $success = $result.AsyncWaitHandle.WaitOne(1000, $false)
        $tcpClient.Close()
        return $success
    } catch {
        return $false
    }
}

function Get-ProcessInfo {
    param([int]$ProcessId)
    try {
        return Get-CimInstance Win32_Process -Filter "ProcessId = $ProcessId" -ErrorAction Stop
    } catch {
        return $null
    }
}

function Should-StopForMarketplace {
    param(
        [object]$ProcessInfo
    )

    if (-not $ProcessInfo) {
        return $false
    }

    $name = if ($ProcessInfo.Name) { $ProcessInfo.Name.ToLowerInvariant() } else { "" }
    $cmd = if ($ProcessInfo.CommandLine) { $ProcessInfo.CommandLine.ToLowerInvariant() } else { "" }
    $repoPath = $repoRoot.ToLowerInvariant()

    if ($name -notin @("node.exe", "node", "powershell.exe", "powershell", "pwsh.exe", "pwsh")) {
        return $false
    }

    if ($cmd.Contains($repoPath)) {
        return $true
    }

    if ($cmd.Contains("medusa develop") -or $cmd.Contains("npm run dev") -or $cmd.Contains("next dev")) {
        return $true
    }

    return $false
}

function Release-Port-Safely {
    param(
        [int]$Port,
        [string]$Label
    )

    $listeners = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess -Unique
    if (-not $listeners) {
        Write-Host "✅ Port $Port is available for $Label" -ForegroundColor Green
        return
    }

    foreach ($ownerPid in $listeners) {
        $procInfo = Get-ProcessInfo -ProcessId $ownerPid
        $procName = if ($procInfo -and $procInfo.Name) { $procInfo.Name } else { "PID $ownerPid" }

        if (Should-StopForMarketplace -ProcessInfo $procInfo) {
            Write-Host "⚠️  Port $Port is used by marketplace process $procName. Stopping it..." -ForegroundColor Yellow
            Stop-Process -Id $ownerPid -Force -ErrorAction SilentlyContinue
            Start-Sleep -Milliseconds 800
            Write-Host "✅ Stopped $procName on port $Port" -ForegroundColor Green
        } else {
            Write-Host "ℹ️  Port $Port is used by external process $procName. Leaving it untouched." -ForegroundColor Cyan
        }
    }
}

function Get-MarketplaceDevProcesses {
    param([string]$RepoPath)

    $repoPathLower = $RepoPath.ToLowerInvariant()
    return Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
        $cmd = if ($_.CommandLine) { $_.CommandLine.ToLowerInvariant() } else { "" }
        if ([string]::IsNullOrWhiteSpace($cmd)) { return $false }
        if (-not $cmd.Contains($repoPathLower)) { return $false }

        return (
            $cmd.Contains("medusa develop") -or
            $cmd.Contains("@medusajs\\cli\\cli.js develop") -or
            $cmd.Contains("@medusajs\\cli\\cli.js start --types") -or
            $cmd.Contains("next dev") -or
            $cmd.Contains("npm run dev")
        )
    }
}

function Stop-StaleMarketplaceDevProcesses {
    param(
        [string]$RepoPath,
        [int]$CurrentPid
    )

    $candidates = Get-MarketplaceDevProcesses -RepoPath $RepoPath |
        Sort-Object ProcessId -Unique |
        Where-Object { $_.ProcessId -ne $CurrentPid }

    foreach ($candidate in $candidates) {
        try {
            Stop-Process -Id $candidate.ProcessId -Force -ErrorAction Stop
            Write-Host "ℹ️  Stopped stale marketplace process PID $($candidate.ProcessId)." -ForegroundColor Gray
        } catch {
            Write-Host "⚠️  Failed to stop stale process PID $($candidate.ProcessId): $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }
}


$pgReady = Test-Port 5432
$redisReady = Test-Port 6379

if (-not $pgReady) {
    Write-Host '❌ PostgreSQL is not running on port 5432' -ForegroundColor Red
    Write-Host '   Please run Start-Dependencies.bat first to start PostgreSQL' -ForegroundColor Yellow
    Write-Host ''
    pause
    exit 1
}

if (-not $redisReady) {
    Write-Host '❌ Redis is not running on port 6379' -ForegroundColor Red
    Write-Host '   Please run Start-Dependencies.bat first to start Redis' -ForegroundColor Yellow
    Write-Host ''
    pause
    exit 1
}

Write-Host '✅ PostgreSQL: Ready' -ForegroundColor Green
Write-Host '✅ Redis: Ready' -ForegroundColor Green
Write-Host ''

Write-Host '[0.5/5] Cleaning stale marketplace dev processes...' -ForegroundColor Yellow
Stop-StaleMarketplaceDevProcesses -RepoPath $repoRoot -CurrentPid $PID
Write-Host ''

# Step 1: Release dev ports without touching unrelated apps
Write-Host '[1/5] Checking for running services...' -ForegroundColor Yellow

Release-Port-Safely -Port $preferredBackendPort -Label "Medusa backend"
Release-Port-Safely -Port $preferredStorefrontPort -Label "Storefront"
Release-Port-Safely -Port $adminUiPort -Label "Admin UI (Vite)"

$port9000InUseAfterStop = Get-NetTCPConnection -LocalPort $preferredBackendPort -ErrorAction SilentlyContinue | Select-Object -First 1
if ($port9000InUseAfterStop) {
    $ownerPid = $port9000InUseAfterStop.OwningProcess
    $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
    $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }

    Write-Host "⚠️  Port $preferredBackendPort is still occupied by $ownerName. Using fallback port $fallbackBackendPort for Medusa." -ForegroundColor Yellow
    $backendPort = $fallbackBackendPort
}

$port8000InUseAfterStop = Get-NetTCPConnection -LocalPort $preferredStorefrontPort -ErrorAction SilentlyContinue | Select-Object -First 1
if ($port8000InUseAfterStop) {
    $ownerPid = $port8000InUseAfterStop.OwningProcess
    $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
    $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }

    Write-Host "⚠️  Port $preferredStorefrontPort is still occupied by $ownerName. Using fallback port $fallbackStorefrontPort for storefront." -ForegroundColor Yellow
    $storefrontPort = $fallbackStorefrontPort
}

if ($backendPort -eq $fallbackBackendPort) {
    Release-Port-Safely -Port $fallbackBackendPort -Label "Medusa backend (fallback)"
    $fallbackBackendInUse = Get-NetTCPConnection -LocalPort $fallbackBackendPort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($fallbackBackendInUse) {
        $ownerPid = $fallbackBackendInUse.OwningProcess
        $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
        $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }
        Write-Host "❌ Fallback backend port $fallbackBackendPort is occupied by external process $ownerName." -ForegroundColor Red
        Write-Host "   Please free port $fallbackBackendPort and retry." -ForegroundColor Yellow
        pause
        exit 1
    }
}

if ($storefrontPort -eq $fallbackStorefrontPort) {
    Release-Port-Safely -Port $fallbackStorefrontPort -Label "Storefront (fallback)"
    $fallbackStorefrontInUse = Get-NetTCPConnection -LocalPort $fallbackStorefrontPort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($fallbackStorefrontInUse) {
        $ownerPid = $fallbackStorefrontInUse.OwningProcess
        $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
        $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }
        Write-Host "❌ Fallback storefront port $fallbackStorefrontPort is occupied by external process $ownerName." -ForegroundColor Red
        Write-Host "   Please free port $fallbackStorefrontPort and retry." -ForegroundColor Yellow
        pause
        exit 1
    }
}
Write-Host ''

# Warn if the admin UI port is still occupied after cleanup (can cause stale admin assets).
$adminUiInUse = Get-NetTCPConnection -LocalPort $adminUiPort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
if ($adminUiInUse) {
    $ownerPid = $adminUiInUse.OwningProcess
    $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
    $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }
    Write-Host "⚠️  Admin UI port $adminUiPort is in use by $ownerName. Medusa may fall back to the built admin bundle." -ForegroundColor Yellow
}

# Step 2: Check if build exists
Write-Host '[2/5] Validating backend build...' -ForegroundColor Yellow
$buildPath = Join-Path $repoRoot ".medusa\server"
$adminPath = Join-Path $buildPath "public\admin\index.html"
if (-not (Test-Path $adminPath)) {
    Write-Host '⚠️  First-time setup detected. Building backend...' -ForegroundColor Yellow
    Write-Host 'This may take 2-3 minutes...
' -ForegroundColor Gray

    Set-Location $repoRoot
    npm run build

    if ($LASTEXITCODE -ne 0) {
        Write-Host '
❌ Build failed. Please check for errors above.' -ForegroundColor Red
        pause
        exit 1
    }
    Write-Host '
✅ Backend build complete!
' -ForegroundColor Green
} else {
    Write-Host '✅ Backend already built' -ForegroundColor Green
}
Write-Host ''

# Step 3: Start Medusa Backend
Write-Host "[3/5] Launching Medusa Backend (:$backendPort)..." -ForegroundColor Green

$adminPath = Get-AdminPathFromConfig -RepoRoot $repoRoot
$backendUrl = "http://localhost:$backendPort"
$storeCors = "http://localhost:8000,http://localhost:$storefrontPort,https://docs.medusajs.com"
$adminCors = "http://localhost:5173,http://localhost:9000,http://localhost:$backendPort,http://localhost:8000,http://localhost:$storefrontPort,https://docs.medusajs.com"
$authCors = "http://localhost:5173,http://localhost:9000,http://localhost:$backendPort,http://localhost:8000,http://localhost:$storefrontPort,https://docs.medusajs.com"

$backendCommand = @"
`$env:PORT='$backendPort'
`$env:MEDUSA_BACKEND_URL='$backendUrl'
`$env:STORE_CORS='$storeCors'
`$env:ADMIN_CORS='$adminCors'
`$env:AUTH_CORS='$authCors'
cd `"$repoRoot`"
npm run dev
"@

$backendProcess = Start-Process powershell -ArgumentList '-NoExit', '-Command', $backendCommand -PassThru

# Wait for Backend to be ready
Write-Host '⏳ Waiting for backend to be ready...' -ForegroundColor Gray

function Wait-ForBackend {
    param(
        [int]$Port
    )

    $maxAttempts = 120  # 2 minutes max
    $healthyStreak = 0
    $attempt = 0
    while ($attempt -lt $maxAttempts) {
        try {
            $response = Invoke-WebRequest -Uri "http://localhost:$Port/health" -TimeoutSec 1 -UseBasicParsing -ErrorAction SilentlyContinue
            if ($response.StatusCode -eq 200) {
                $healthyStreak++
                if ($healthyStreak -ge 3) {
                    Write-Host "✅ Backend is ready!" -ForegroundColor Green
                    return $true
                }
            } else {
                $healthyStreak = 0
            }
        } catch {
            $healthyStreak = 0
            # Not ready yet, keep waiting
        }
        Start-Sleep -Seconds 1
        $attempt++

        # Print progress every 10 seconds
        if ($attempt % 10 -eq 0) {
            Write-Host "⏳ Still waiting... ($attempt seconds)" -ForegroundColor Gray
        }
    }
    Write-Host "❌ Backend failed to start after 2 minutes" -ForegroundColor Red
    return $false
}

function Resolve-StorefrontPublishableKey {
    param([string]$RepoRoot)

    try {
        $cliPath = Join-Path $RepoRoot "node_modules\@medusajs\cli\cli.js"
        if (-not (Test-Path $cliPath)) {
            Write-Host "⚠️  Medusa CLI not found at $cliPath" -ForegroundColor Yellow
            return $null
        }

        Push-Location $RepoRoot
        try {
            $output = & node $cliPath exec ./src/scripts/ensure-storefront-publishable-key.ts 2>&1
        } finally {
            Pop-Location
        }
        $keyLine = $output | Where-Object { $_ -like "PUBLISHABLE_KEY=*" } | Select-Object -Last 1

        if ($keyLine) {
            return $keyLine.Substring("PUBLISHABLE_KEY=".Length).Trim()
        }

        Write-Host "⚠️  Could not parse publishable key from script output." -ForegroundColor Yellow
        return $null
    } catch {
        Write-Host "⚠️  Failed to create publishable key automatically: $($_.Exception.Message)" -ForegroundColor Yellow
        return $null
    }
}

if (-not (Wait-ForBackend -Port $backendPort)) {
    Write-Host "Backend did not respond. Check the terminal window for errors." -ForegroundColor Red
    pause
    exit 1
}

# Step 4: Start Next.js Storefront
Write-Host "[4/5] Launching Next.js Storefront (:$storefrontPort)..." -ForegroundColor Green
$storefrontPublishableKey = Resolve-StorefrontPublishableKey -RepoRoot $repoRoot

if (-not $storefrontPublishableKey) {
    Write-Host "❌ Storefront requires a valid Medusa publishable key, but none was resolved." -ForegroundColor Red
    Write-Host "   Run: npm run seed" -ForegroundColor Yellow
    pause
    exit 1
}

$storefrontCommand = @"
`$env:MEDUSA_BACKEND_URL='$backendUrl'
`$env:NEXT_PUBLIC_MEDUSA_BACKEND_URL='$backendUrl'
`$env:NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY='$storefrontPublishableKey'
cd `"$storefrontRoot`"
npm run dev -- -p $storefrontPort
"@
Start-Process powershell -ArgumentList '-NoExit', '-Command', $storefrontCommand

# Step 5: Key Registration & Launch
Write-Host '[5/5] Registering runtime configuration...' -ForegroundColor Green

Update-LauncherRuntimeConfig -RepoRoot $repoRoot -BackendPort $backendPort -StorefrontPort $storefrontPort -AdminPath $adminPath

Write-Host 'Opening Command Center Interface...' -ForegroundColor Green
Start-Sleep -Seconds 3
$encodedAdminPath = [System.Uri]::EscapeDataString($adminPath)
$launcherUri = "file:///" + (($launcherHtml -replace '\\', '/') -replace ' ', '%20') + "?backendPort=$backendPort&storefrontPort=$storefrontPort&adminPath=$encodedAdminPath"
Start-Process $launcherUri

Write-Host '
===================================================' -ForegroundColor Cyan
Write-Host '✅ All systems deployed successfully!' -ForegroundColor Green
Write-Host '===================================================
' -ForegroundColor Cyan
Write-Host '📊 Monitor the PowerShell windows for startup logs' -ForegroundColor Yellow
Write-Host '🌐 Command Center opening in your browser...' -ForegroundColor Yellow
$adminUrl = "$backendUrl$adminPath"
Write-Host "🔐 Admin URL: $adminUrl" -ForegroundColor Yellow
Write-Host "🛍️  Storefront URL: http://localhost:$storefrontPort" -ForegroundColor Yellow
Write-Host '
⏳ Services may take 30-60 seconds to fully initialize' -ForegroundColor Gray
Write-Host ''
