#!/usr/bin/env pwsh
# TheRxSpot Marketplace - Admin Only Launcher
$ErrorActionPreference = "Stop"
# Suppress Invoke-WebRequest progress rendering, which can look like a hang.
$ProgressPreference = "SilentlyContinue"

Write-Host ""
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "   TheRxSpot Marketplace | Admin-Only Launcher" -ForegroundColor Cyan
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host ""

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot ".")).Path
$preferredBackendPort = 9000
$fallbackBackendPort = 9001
$backendPort = $preferredBackendPort
$adminUiPort = 5173
$runtimeConfigPath = Join-Path $repoRoot "launcher_assets\runtime-config.js"
$requestedMode = if ($env:THERXSPOT_BACKEND_MODE) { $env:THERXSPOT_BACKEND_MODE } else { "start" }
$requestedMode = $requestedMode.ToLowerInvariant()
$backendMode = if ($requestedMode -in @("dev", "start")) { $requestedMode } else { "start" }
$backendNpmScript = if ($backendMode -eq "dev") { "dev" } else { "start" }

function Get-AdminPathFromConfig {
    param([string]$RepoRoot)

    $configPath = Join-Path $RepoRoot "medusa-config.ts"
    if (-not (Test-Path $configPath)) {
        return "/app"
    }

    $content = Get-Content $configPath -Raw
    if ($content -match 'path:\s*"([^"]+)"') {
        $path = $matches[1].Trim()
        if (-not $path.StartsWith("/")) {
            $path = "/$path"
        }
        if ($path.Length -gt 1 -and $path.EndsWith("/")) {
            $path = $path.TrimEnd("/")
        }
        return $path
    }

    return "/app"
}

function Try-GetRuntimePort {
    param(
        [string]$ConfigPath,
        [string]$Key
    )

    if (-not (Test-Path $ConfigPath)) {
        return $null
    }

    $content = Get-Content $ConfigPath -Raw
    if ($content -match "$Key\\s*:\\s*(\\d+)") {
        return [int]$matches[1]
    }

    return $null
}

function Get-EnvValueFromDotEnv {
    param(
        [string]$EnvPath,
        [string]$Key
    )

    if (-not (Test-Path $EnvPath)) {
        return $null
    }

    $pattern = "^\s*" + [regex]::Escape($Key) + "\s*=\s*(.*)$"
    foreach ($line in Get-Content $EnvPath) {
        if ($line -match $pattern) {
            $value = $matches[1].Trim()
            if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
                $value = $value.Substring(1, $value.Length - 2)
            }
            return $value
        }
    }

    return $null
}

function Convert-ToSha256Hex {
    param([string]$Value)

    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
        $hash = $sha.ComputeHash($bytes)
        return ($hash | ForEach-Object { $_.ToString("x2") }) -join ""
    } finally {
        $sha.Dispose()
    }
}

function Resolve-EncryptionKeyForLauncher {
    param([string]$RepoRoot)

    $candidate = if ($env:ENCRYPTION_KEY_CURRENT) { $env:ENCRYPTION_KEY_CURRENT } else { $env:DATABASE_ENCRYPTION_KEY }
    if (-not [string]::IsNullOrWhiteSpace($candidate)) {
        return $candidate.Trim()
    }

    $envPath = Join-Path $RepoRoot ".env"

    $fromFile = Get-EnvValueFromDotEnv -EnvPath $envPath -Key "ENCRYPTION_KEY_CURRENT"
    if (-not [string]::IsNullOrWhiteSpace($fromFile)) {
        return $fromFile.Trim()
    }

    $legacyFromFile = Get-EnvValueFromDotEnv -EnvPath $envPath -Key "DATABASE_ENCRYPTION_KEY"
    if (-not [string]::IsNullOrWhiteSpace($legacyFromFile)) {
        return $legacyFromFile.Trim()
    }

    $seed = Get-EnvValueFromDotEnv -EnvPath $envPath -Key "JWT_SECRET"
    if ([string]::IsNullOrWhiteSpace($seed)) {
        $seed = Get-EnvValueFromDotEnv -EnvPath $envPath -Key "COOKIE_SECRET"
    }
    if ([string]::IsNullOrWhiteSpace($seed)) {
        return $null
    }

    $seed = $seed.Trim()
    if ($seed -match "^[0-9a-fA-F]{64,}$") {
        return $seed.Substring(0, 64).ToLowerInvariant()
    }

    return (Convert-ToSha256Hex -Value $seed)
}

function Update-LauncherRuntimeConfig {
    param(
        [string]$RepoRoot,
        [int]$BackendPort,
        [int]$StorefrontPort,
        [string]$AdminPath
    )

    $normalizedAdminPath = if ([string]::IsNullOrWhiteSpace($AdminPath)) { "/app" } else { $AdminPath.Trim() }
    if (-not $normalizedAdminPath.StartsWith("/")) {
        $normalizedAdminPath = "/$normalizedAdminPath"
    }
    if ($normalizedAdminPath.Length -gt 1 -and $normalizedAdminPath.EndsWith("/")) {
        $normalizedAdminPath = $normalizedAdminPath.TrimEnd("/")
    }

    $runtimeConfigContent = @"
// Auto-generated by Launch-Admin-Only.ps1
window.__THERXSPOT_LAUNCHER_PORTS = {
  backendPort: $BackendPort,
  storefrontPort: $StorefrontPort,
  adminPath: "$normalizedAdminPath",
  generatedAt: "$(Get-Date -Format "yyyy-MM-ddTHH:mm:ss")"
};
"@

    Set-Content -Path (Join-Path $RepoRoot "launcher_assets\runtime-config.js") -Value $runtimeConfigContent -Encoding utf8
}

function Sync-AdminBuildForStartMode {
    param([string]$RepoRoot)

    $sourceDir = Join-Path $RepoRoot ".medusa\server\public\admin"
    $sourceIndex = Join-Path $sourceDir "index.html"
    if (-not (Test-Path $sourceIndex)) {
        return $false
    }

    $targetDir = Join-Path $RepoRoot "public\admin"
    New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    Copy-Item -Path (Join-Path $sourceDir "*") -Destination $targetDir -Recurse -Force
    return $true
}

function Test-Port {
    param([int]$Port)
    try {
        $tcpClient = New-Object System.Net.Sockets.TcpClient
        $tcpClient.ReceiveTimeout = 1000
        $tcpClient.SendTimeout = 1000
        $result = $tcpClient.BeginConnect("127.0.0.1", $Port, $null, $null)
        $success = $result.AsyncWaitHandle.WaitOne(1000, $false)
        $tcpClient.Close()
        return $success
    } catch {
        return $false
    }
}

function Get-ProcessInfo {
    param([int]$ProcessId)
    try {
        return Get-CimInstance Win32_Process -Filter "ProcessId = $ProcessId" -ErrorAction Stop
    } catch {
        return $null
    }
}

function Should-StopForMarketplace {
    param([object]$ProcessInfo)

    if (-not $ProcessInfo) { return $false }

    $name = if ($ProcessInfo.Name) { $ProcessInfo.Name.ToLowerInvariant() } else { "" }
    $cmd = if ($ProcessInfo.CommandLine) { $ProcessInfo.CommandLine.ToLowerInvariant() } else { "" }
    $repoPath = $repoRoot.ToLowerInvariant()

    if ($name -notin @("node.exe", "node", "powershell.exe", "powershell", "pwsh.exe", "pwsh")) {
        return $false
    }

    if ($cmd.Contains($repoPath)) { return $true }
    if (
        $cmd.Contains("medusa develop") -or
        $cmd.Contains("medusa start") -or
        $cmd.Contains("@medusajs\\cli\\cli.js develop") -or
        $cmd.Contains("@medusajs\\cli\\cli.js") -or
        $cmd.Contains("@medusajs\\cli\\cli.js start") -or
        $cmd.Contains("@medusajs\\cli\\cli.js start --types") -or
        $cmd.Contains("npm run dev") -or
        $cmd.Contains("npm run start")
    ) {
        return $true
    }

    return $false
}

function Release-Port-Safely {
    param([int]$Port, [string]$Label)

    $listeners = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
        Select-Object -ExpandProperty OwningProcess -Unique

    if (-not $listeners) {
        Write-Host "OK: Port $Port is available for $Label" -ForegroundColor Green
        return
    }

    foreach ($ownerPid in $listeners) {
        $procInfo = Get-ProcessInfo -ProcessId $ownerPid
        $procName = if ($procInfo -and $procInfo.Name) { $procInfo.Name } else { "PID $ownerPid" }

        if (Should-StopForMarketplace -ProcessInfo $procInfo) {
            Write-Host "WARN: Port $Port is used by marketplace process $procName. Stopping it..." -ForegroundColor Yellow
            Stop-MarketplaceProcessTree -ProcessId $ownerPid | Out-Null
            Start-Sleep -Milliseconds 800
        } else {
            Write-Host "INFO: Port $Port is used by external process $procName. Leaving it untouched." -ForegroundColor Cyan
        }
    }
}

function Stop-MarketplaceProcessTree {
    param([int]$ProcessId)

    if ($ProcessId -le 0) {
        return $false
    }

    try {
        $null = & taskkill /PID $ProcessId /T /F 2>$null
        return $true
    } catch {
        try {
            Stop-Process -Id $ProcessId -Force -ErrorAction Stop
            return $true
        } catch {
            return $false
        }
    }
}

function Get-MarketplaceDevProcesses {
    param([string]$RepoPath)

    $repoPathLower = $RepoPath.ToLowerInvariant()
    return Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
        $cmd = if ($_.CommandLine) { $_.CommandLine.ToLowerInvariant() } else { "" }
        if ([string]::IsNullOrWhiteSpace($cmd)) { return $false }

        # Catch stale Medusa develop/start children that may not include repo path
        # in their commandline (for example: "cmd /c medusa develop").
        if (
            $cmd.Contains("medusa develop") -or
            $cmd.Contains("medusa start") -or
            $cmd.Contains("@medusajs\\cli\\cli.js develop") -or
            $cmd.Contains("@medusajs\\cli\\cli.js") -or
            $cmd.Contains("@medusajs\\cli\\cli.js start") -or
            $cmd.Contains("@medusajs\\cli\\cli.js start --types")
        ) {
            return $true
        }

        # Keep npm-based cleanup scoped to this repository path.
        if ($cmd.Contains($repoPathLower) -and ($cmd.Contains("npm run dev") -or $cmd.Contains("npm run start"))) {
            return $true
        }

        return $false
    }
}

function Test-IsProcessDescendant {
    param(
        [int]$ProcessId,
        [int]$AncestorPid
    )

    if ($ProcessId -le 0 -or $AncestorPid -le 0) {
        return $false
    }

    $currentPid = $ProcessId
    for ($i = 0; $i -lt 30; $i++) {
        if ($currentPid -eq $AncestorPid) {
            return $true
        }

        try {
            $proc = Get-CimInstance Win32_Process -Filter "ProcessId = $currentPid" -ErrorAction Stop
        } catch {
            return $false
        }

        if (-not $proc -or -not $proc.ParentProcessId -or $proc.ParentProcessId -eq 0) {
            return $false
        }

        $currentPid = [int]$proc.ParentProcessId
    }

    return $false
}

function Stop-StaleMarketplaceDevProcesses {
    param(
        [string]$RepoPath,
        [int]$CurrentPid
    )

    $candidates = Get-MarketplaceDevProcesses -RepoPath $RepoPath |
        Sort-Object ProcessId -Unique |
        Where-Object { $_.ProcessId -ne $CurrentPid }

    foreach ($candidate in $candidates) {
        try {
            if (Stop-MarketplaceProcessTree -ProcessId $candidate.ProcessId) {
                Write-Host "INFO: Stopped stale marketplace process PID $($candidate.ProcessId)." -ForegroundColor Gray
            } else {
                Write-Host "WARN: Failed to stop stale process PID $($candidate.ProcessId)." -ForegroundColor Yellow
            }
        } catch {
            Write-Host "WARN: Failed to stop stale process PID $($candidate.ProcessId): $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }
}

function Wait-ForBackend {
    param(
        [int]$Port,
        [int]$BackendShellPid
    )

    # Startup can be slow on large repos (or during watcher restarts), so keep this generous.
    $maxAttempts = 360
    $healthyStreak = 0
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        if ($BackendShellPid -gt 0) {
            $backendShell = Get-Process -Id $BackendShellPid -ErrorAction SilentlyContinue
            if (-not $backendShell) {
                Write-Host "ERROR: Backend shell process exited before health checks passed." -ForegroundColor Red
                return $false
            }
        }

        try {
            $response = Invoke-WebRequest -Uri "http://localhost:$Port/health" -TimeoutSec 2 -UseBasicParsing -ErrorAction Stop
            if ($response.StatusCode -eq 200) {
                $healthyStreak++
                if ($healthyStreak -ge 3) {
                    Write-Host "OK: Backend is healthy on port $Port" -ForegroundColor Green
                    return $true
                }
            } else {
                $healthyStreak = 0
            }
        } catch {
            $healthyStreak = 0

            # Fail fast when another process captured the target backend port.
            $listener = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
                Select-Object -First 1
            if ($listener) {
                $ownerPid = [int]$listener.OwningProcess
                $isOwnedByBackendShellTree = Test-IsProcessDescendant -ProcessId $ownerPid -AncestorPid $BackendShellPid

                if (-not $isOwnedByBackendShellTree) {
                    $ownerInfo = Get-ProcessInfo -ProcessId $ownerPid
                    $ownerName = if ($ownerInfo -and $ownerInfo.Name) { $ownerInfo.Name } else { "PID $ownerPid" }
                    Write-Host "ERROR: Port $Port is owned by non-launcher process $ownerName while waiting for backend health." -ForegroundColor Red
                    return $false
                }
            }

            if ($attempt % 10 -eq 0) {
                Write-Host "Waiting for backend... ($attempt seconds)" -ForegroundColor Gray
            }
            if ($attempt % 30 -eq 0) {
                Write-Host "INFO: If file watchers are restarting the dev server, startup can take several minutes." -ForegroundColor DarkGray
            }
        }
        Start-Sleep -Seconds 1
    }

    return $false
}

function Prewarm-Admin {
    param(
        [int]$Port,
        [string]$AdminPath
    )

    $basePath = if ($AdminPath.StartsWith("/")) { $AdminPath } else { "/$AdminPath" }
    $urls = @(
        "http://localhost:$Port$basePath",
        "http://localhost:$Port$basePath/@vite/client",
        "http://localhost:$Port$basePath/entry.jsx"
    )

    foreach ($url in $urls) {
        try {
            $null = Invoke-WebRequest -Uri $url -TimeoutSec 20 -UseBasicParsing -ErrorAction Stop
        } catch {
            Write-Host "WARN: Prewarm request failed: $url" -ForegroundColor Yellow
        }
    }
}

function Open-AdminUrl {
    param([string]$Url)

    $edgeCommand = Get-Command "msedge.exe" -ErrorAction SilentlyContinue
    $edgePath = if ($edgeCommand) { $edgeCommand.Source } else { $null }

    if (-not $edgePath) {
        $edgeCandidates = @(
            "C:\Program Files\Microsoft\Edge\Application\msedge.exe",
            "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
        )
        foreach ($candidate in $edgeCandidates) {
            if (Test-Path $candidate) {
                $edgePath = $candidate
                break
            }
        }
    }

    if ($edgePath) {
        $args = @(
            "--new-window",
            "--inprivate",
            "--disable-extensions",
            $Url
        )
        Start-Process -FilePath $edgePath -ArgumentList $args
        return
    }

    $chromePath = $null
    $chromeCandidates = @(
        "C:\Program Files\Google\Chrome\Application\chrome.exe",
        "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
    )
    foreach ($candidate in $chromeCandidates) {
        if (Test-Path $candidate) {
            $chromePath = $candidate
            break
        }
    }

    if ($chromePath) {
        $args = @(
            "--new-window",
            "--incognito",
            "--disable-extensions",
            $Url
        )
        Start-Process -FilePath $chromePath -ArgumentList $args
        return
    }

    Write-Host "WARN: No Edge/Chrome executable found via PATH or standard install paths. Opening default browser profile." -ForegroundColor Yellow
    Start-Process $Url
}

Write-Host ("Mode: backend '" + $backendNpmScript + "' (set THERXSPOT_BACKEND_MODE=dev for hot-reload mode)") -ForegroundColor Gray
Write-Host ""

Write-Host "[1/5] Checking dependencies..." -ForegroundColor Yellow
$pgReady = Test-Port -Port 5432
$redisReady = Test-Port -Port 6379

if (-not $pgReady) {
    Write-Host "ERROR: PostgreSQL is not running on port 5432" -ForegroundColor Red
    Write-Host "Run .\Start-Dependencies.bat first." -ForegroundColor Yellow
    pause
    exit 1
}

if (-not $redisReady) {
    Write-Host "ERROR: Redis is not running on port 6379" -ForegroundColor Red
    Write-Host "Run .\Start-Dependencies.bat first." -ForegroundColor Yellow
    pause
    exit 1
}

Write-Host "OK: PostgreSQL and Redis are ready" -ForegroundColor Green

Write-Host "[1.5/5] Cleaning stale marketplace dev processes..." -ForegroundColor Yellow
Stop-StaleMarketplaceDevProcesses -RepoPath $repoRoot -CurrentPid $PID

Write-Host "[2/5] Resolving backend port..." -ForegroundColor Yellow
Release-Port-Safely -Port $preferredBackendPort -Label "Medusa backend"
Release-Port-Safely -Port $adminUiPort -Label "Admin UI (Vite)"

$port9000InUse = Get-NetTCPConnection -LocalPort $preferredBackendPort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
if ($port9000InUse) {
    $ownerPid = $port9000InUse.OwningProcess
    $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
    $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }
    Write-Host "WARN: Port $preferredBackendPort is still occupied by $ownerName. Using $fallbackBackendPort." -ForegroundColor Yellow
    $backendPort = $fallbackBackendPort
}

if ($backendPort -eq $fallbackBackendPort) {
    Release-Port-Safely -Port $fallbackBackendPort -Label "Medusa backend (fallback)"
    $fallbackInUse = Get-NetTCPConnection -LocalPort $fallbackBackendPort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($fallbackInUse) {
        $ownerPid = $fallbackInUse.OwningProcess
        $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
        $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }
        Write-Host "ERROR: Fallback backend port $fallbackBackendPort is occupied by external process $ownerName." -ForegroundColor Red
        Write-Host "Close the external process or free port $fallbackBackendPort before launching admin." -ForegroundColor Yellow
        pause
        exit 1
    }
}

$adminUiInUse = Get-NetTCPConnection -LocalPort $adminUiPort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
if ($adminUiInUse) {
    $ownerPid = $adminUiInUse.OwningProcess
    $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
    $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }
    Write-Host "WARN: Admin UI port $adminUiPort is in use by $ownerName. Admin may load stale built assets." -ForegroundColor Yellow
}

Write-Host "[3/5] Ensuring backend build exists..." -ForegroundColor Yellow
$adminBuildIndex = Join-Path $repoRoot ".medusa\server\public\admin\index.html"
$adminPath = Get-AdminPathFromConfig -RepoRoot $repoRoot

# Check if we need to rebuild because of port change or missing build
$needRebuild = -not (Test-Path $adminBuildIndex)

if (-not $needRebuild) {
    $adminIndexContent = Get-Content -Path $adminBuildIndex -Raw
    $expectedAssetPath = "$adminPath/assets/"
    if ($adminIndexContent -notmatch [regex]::Escape($expectedAssetPath)) {
        Write-Host "WARN: Admin build path does not match configured admin path ($adminPath). Rebuild required." -ForegroundColor Yellow
        $needRebuild = $true
    }
}

if (-not $needRebuild) {
    $adminSourceDir = Join-Path $repoRoot "src\admin"
    $adminConfigFile = Join-Path $repoRoot "medusa-config.ts"

    $latestSourceWrite = $null
    if (Test-Path $adminSourceDir) {
        $latestSourceFile = Get-ChildItem -Path $adminSourceDir -Recurse -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTimeUtc -Descending |
            Select-Object -First 1
        if ($latestSourceFile) {
            $latestSourceWrite = $latestSourceFile.LastWriteTimeUtc
        }
    }

    if ((Test-Path $adminConfigFile)) {
        $configWrite = (Get-Item $adminConfigFile).LastWriteTimeUtc
        if (-not $latestSourceWrite -or $configWrite -gt $latestSourceWrite) {
            $latestSourceWrite = $configWrite
        }
    }

    $buildWrite = (Get-Item $adminBuildIndex).LastWriteTimeUtc
    if ($latestSourceWrite -and $latestSourceWrite -gt $buildWrite) {
        Write-Host "WARN: Admin source is newer than built admin bundle. Rebuild required." -ForegroundColor Yellow
        $needRebuild = $true
    }
}

# When backend falls back to a non-default port (e.g., 9001), force a rebuild so
# the admin bundle points at the active backend URL and doesn't call stale :9000.
if (-not $needRebuild -and $backendPort -ne $preferredBackendPort) {
    Write-Host "WARN: Backend is on fallback port $backendPort. Forcing admin rebuild for backend URL sync." -ForegroundColor Yellow
    $needRebuild = $true
}

if ($needRebuild) {
    Write-Host "Rebuilding admin panel for port $backendPort..." -ForegroundColor Yellow
    Write-Host "This ensures the white screen issue is resolved." -ForegroundColor Gray
    
    Set-Location $repoRoot
    $env:MEDUSA_BACKEND_URL = "http://localhost:$backendPort"

    # Isolate TEMP/TMP for build to avoid intermittent esbuild temp-file locks on Windows.
    $buildTempDir = Join-Path $repoRoot ".tmp\launcher-build-temp"
    New-Item -ItemType Directory -Path $buildTempDir -Force | Out-Null
    $previousTemp = $env:TEMP
    $previousTmp = $env:TMP
    $env:TEMP = $buildTempDir
    $env:TMP = $buildTempDir

    try {
        npm run build
    } finally {
        $env:TEMP = $previousTemp
        $env:TMP = $previousTmp
    }
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Build failed." -ForegroundColor Red
        pause
        exit 1
    }
    Write-Host "OK: Build complete" -ForegroundColor Green
} else {
    Write-Host "OK: Admin build is available and valid" -ForegroundColor Green
}

if ($backendMode -eq "start") {
    Write-Host "Syncing admin static assets for production start mode..." -ForegroundColor Gray
    if (-not (Sync-AdminBuildForStartMode -RepoRoot $repoRoot)) {
        Write-Host "ERROR: Admin build artifacts are missing. Run npm run build and retry." -ForegroundColor Red
        pause
        exit 1
    }
}

Write-Host "[4/5] Starting Medusa backend on :$backendPort..." -ForegroundColor Yellow
$backendUrl = "http://localhost:$backendPort"
$storeCors = "http://localhost:8000,http://localhost:8001,https://docs.medusajs.com"
$adminCors = "http://localhost:5173,http://localhost:9000,http://localhost:$backendPort,http://localhost:8000,http://localhost:8001,https://docs.medusajs.com"
$authCors = "http://localhost:5173,http://localhost:9000,http://localhost:$backendPort,http://localhost:8000,http://localhost:8001,https://docs.medusajs.com"
$resolvedEncryptionKey = Resolve-EncryptionKeyForLauncher -RepoRoot $repoRoot

if ([string]::IsNullOrWhiteSpace($resolvedEncryptionKey) -and $backendMode -eq "start") {
    Write-Host "ERROR: Missing encryption key for production start mode." -ForegroundColor Red
    Write-Host "Set ENCRYPTION_KEY_CURRENT (or DATABASE_ENCRYPTION_KEY) in .env to a 32-byte key." -ForegroundColor Yellow
    pause
    exit 1
}

$escapedEncryptionKey = if ([string]::IsNullOrWhiteSpace($resolvedEncryptionKey)) { "" } else { $resolvedEncryptionKey.Replace("'", "''") }

$backendCommand = @"
`$env:PORT='$backendPort'
`$env:MEDUSA_BACKEND_URL='$backendUrl'
`$env:STORE_CORS='$storeCors'
`$env:ADMIN_CORS='$adminCors'
`$env:AUTH_CORS='$authCors'
`$env:ENCRYPTION_KEY_CURRENT='$escapedEncryptionKey'
cd `"$repoRoot`"
npm run $backendNpmScript
"@

$backendProcess = Start-Process powershell -ArgumentList '-Command', $backendCommand -PassThru
Write-Host "Backend process started (PID: $($backendProcess.Id))" -ForegroundColor Gray

if (-not (Wait-ForBackend -Port $backendPort -BackendShellPid $backendProcess.Id)) {
    Write-Host "ERROR: Backend did not become healthy in time." -ForegroundColor Red
    pause
    exit 1
}

Write-Host "Pre-warming admin assets..." -ForegroundColor Gray
Prewarm-Admin -Port $backendPort -AdminPath $adminPath

$runtimeStorefrontPort = Try-GetRuntimePort -ConfigPath $runtimeConfigPath -Key "storefrontPort"
if (-not $runtimeStorefrontPort) {
    $runtimeStorefrontPort = 8000
}
Update-LauncherRuntimeConfig -RepoRoot $repoRoot -BackendPort $backendPort -StorefrontPort $runtimeStorefrontPort -AdminPath $adminPath

Write-Host "[5/5] Opening Admin URL..." -ForegroundColor Yellow
$adminLoginPath = if ($adminPath -eq "/") { "/login" } else { "$adminPath/login" }
$adminUrl = "http://localhost:$backendPort$adminLoginPath"
Open-AdminUrl -Url $adminUrl

Write-Host ""
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "SUCCESS: Admin-only environment is ready" -ForegroundColor Green
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "Admin URL: $adminUrl" -ForegroundColor Yellow
Write-Host ""
