#!/usr/bin/env pwsh
# TheRxSpot Marketplace - Storefront Only Launcher
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "   TheRxSpot Marketplace | Storefront-Only Launcher" -ForegroundColor Cyan
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host ""

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot ".")).Path
$storefrontRoot = Join-Path $repoRoot "TheRxSpot_Marketplace-storefront"
$runtimeConfigPath = Join-Path $repoRoot "launcher_assets\runtime-config.js"
$runtimeHelpersPath = Join-Path $repoRoot "scripts\smoke\runtime-config.ps1"
if (Test-Path $runtimeHelpersPath) {
    . $runtimeHelpersPath
}

$runtimeConfig = $null
if (Get-Command Get-LauncherRuntimeConfig -ErrorAction SilentlyContinue) {
    $runtimeConfig = Get-LauncherRuntimeConfig -RepoRoot $repoRoot
}

$preferredStorefrontPort = if ($runtimeConfig -and $runtimeConfig.StorefrontPort) { [int]$runtimeConfig.StorefrontPort } else { 8000 }
$fallbackStorefrontPort = $preferredStorefrontPort + 1
$storefrontPort = $preferredStorefrontPort
$backendUrl = if ($runtimeConfig -and $runtimeConfig.BackendPort) { "http://localhost:$($runtimeConfig.BackendPort)" } else { "http://localhost:9001" }
$launcherDebug = ($env:THERXSPOT_DEBUG_LAUNCHER -eq "1")
$noBrowser = ($env:THERXSPOT_NO_BROWSER -eq "1")

function Get-ProcessInfo {
    param([int]$ProcessId)
    try {
        return Get-CimInstance Win32_Process -Filter "ProcessId = $ProcessId" -ErrorAction Stop
    } catch {
        return $null
    }
}

function Should-StopForStorefront {
    param([object]$ProcessInfo)

    if (-not $ProcessInfo) { return $false }

    $name = if ($ProcessInfo.Name) { $ProcessInfo.Name.ToLowerInvariant() } else { "" }
    $cmd = if ($ProcessInfo.CommandLine) { $ProcessInfo.CommandLine.ToLowerInvariant() } else { "" }
    $repoPath = $repoRoot.ToLowerInvariant()

    if ($name -notin @("node.exe", "node", "powershell.exe", "powershell", "pwsh.exe", "pwsh")) {
        return $false
    }

    if ($cmd.Contains($repoPath) -and $cmd.Contains("next")) { return $true }
    if ($cmd.Contains("npm run dev") -and $cmd.Contains("next")) { return $true }
    return $false
}

function Release-Port-Safely {
    param([int]$Port)

    $listeners = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
        Select-Object -ExpandProperty OwningProcess -Unique

    if (-not $listeners) {
        Write-Host "OK: Port $Port is available" -ForegroundColor Green
        return
    }

    foreach ($ownerPid in $listeners) {
        $procInfo = Get-ProcessInfo -ProcessId $ownerPid
        $procName = if ($procInfo -and $procInfo.Name) { $procInfo.Name } else { "PID $ownerPid" }
        if (Should-StopForStorefront -ProcessInfo $procInfo) {
            Write-Host "WARN: Port $Port is used by storefront process $procName. Stopping it..." -ForegroundColor Yellow
            Stop-Process -Id $ownerPid -Force -ErrorAction SilentlyContinue
            Start-Sleep -Milliseconds 800
        } elseif ($Port -eq 9000) {
            Write-Host "CRITICAL: Port 9000 is reserved for User IDE. Skipping cleanup." -ForegroundColor Red
        } else {
            Write-Host "INFO: Port $Port is occupied by external process $procName. Using fallback." -ForegroundColor Cyan
        }
    }
}

function Wait-ForStorefront {
    param([int]$Port)

    $maxAttempts = 180
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        $listener = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($listener) {
            Write-Host "OK: Storefront dev server is listening on port $Port" -ForegroundColor Green
            return $true
        }

        if ($attempt % 10 -eq 0) {
            Write-Host "Waiting for storefront... ($attempt seconds)" -ForegroundColor Gray
        }
        Start-Sleep -Seconds 1
    }

    return $false
}

function Update-LauncherRuntimeConfig {
    param(
        [string]$RepoRoot,
        [int]$BackendPort,
        [int]$StorefrontPort,
        [string]$AdminPath
    )

    $normalizedAdminPath = if ([string]::IsNullOrWhiteSpace($AdminPath)) { "/app" } else { $AdminPath.Trim() }
    if (-not $normalizedAdminPath.StartsWith("/")) {
        $normalizedAdminPath = "/$normalizedAdminPath"
    }
    if ($normalizedAdminPath.Length -gt 1 -and $normalizedAdminPath.EndsWith("/")) {
        $normalizedAdminPath = $normalizedAdminPath.TrimEnd("/")
    }

    $runtimeConfigContent = @"
// Auto-generated by Launch-Storefront-Only.ps1
window.__THERXSPOT_LAUNCHER_PORTS = {
  backendPort: $BackendPort,
  storefrontPort: $StorefrontPort,
  adminPath: "$normalizedAdminPath",
  generatedAt: "$(Get-Date -Format "yyyy-MM-ddTHH:mm:ss")"
};
"@

    Set-Content -Path $runtimeConfigPath -Value $runtimeConfigContent -Encoding utf8
}

function Resolve-BackendUrl {
    $candidatePorts = New-Object System.Collections.Generic.List[int]
    if ($runtimeConfig -and $runtimeConfig.BackendPort) {
        $candidatePorts.Add([int]$runtimeConfig.BackendPort)
    }
    foreach ($port in @(9001, 9002)) {
        if (-not $candidatePorts.Contains($port)) {
            $candidatePorts.Add($port)
        }
    }

    $maxAttempts = 45
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        foreach ($port in $candidatePorts) {
            if ($launcherDebug) {
                Write-Host "DEBUG: attempt $attempt probing backend port $port" -ForegroundColor DarkGray
            }
            $listener = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
            if (-not $listener) {
                if ($launcherDebug) {
                    Write-Host "DEBUG: no listener on $port" -ForegroundColor DarkGray
                }
                continue
            }

            foreach ($path in @("/ready", "/health", "/app/login")) {
                try {
                    $response = Invoke-WebRequest -Uri "http://localhost:$port$path" -TimeoutSec 2 -UseBasicParsing -ErrorAction Stop
                    if ($launcherDebug) {
                        Write-Host "DEBUG: $port$path -> $($response.StatusCode)" -ForegroundColor DarkGray
                    }
                    if ($response.StatusCode -ne 200) {
                        continue
                    }

                    return "http://localhost:$port"
                } catch {
                    if ($launcherDebug) {
                        Write-Host "DEBUG: $port$path failed: $($_.Exception.Message)" -ForegroundColor DarkGray
                    }
                    # Keep trying next candidate
                }
            }
        }

        if ($attempt -lt $maxAttempts) {
            Start-Sleep -Seconds 1
        }
    }

    return $null
}

function Resolve-StorefrontPublishableKey {
    try {
        $cliPath = Join-Path $repoRoot "node_modules\@medusajs\cli\cli.js"
        if (-not (Test-Path $cliPath)) {
            Write-Host "WARN: Medusa CLI not found at $cliPath" -ForegroundColor Yellow
            return $null
        }

        Push-Location $repoRoot
        try {
            $output = & node $cliPath exec ./src/scripts/ensure-storefront-publishable-key.ts 2>&1
        } finally {
            Pop-Location
        }
        $keyLine = $output | Where-Object { $_ -like "PUBLISHABLE_KEY=*" } | Select-Object -Last 1

        if ($keyLine) {
            return $keyLine.Substring("PUBLISHABLE_KEY=".Length).Trim()
        }

        Write-Host "WARN: Could not parse publishable key from script output." -ForegroundColor Yellow
        return $null
    } catch {
        Write-Host "WARN: Failed to create publishable key automatically: $($_.Exception.Message)" -ForegroundColor Yellow
        return $null
    }
}

Write-Host "[1/3] Resolving storefront port..." -ForegroundColor Yellow
Release-Port-Safely -Port $preferredStorefrontPort

$port8000InUse = Get-NetTCPConnection -LocalPort $preferredStorefrontPort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
if ($port8000InUse) {
    $ownerPid = $port8000InUse.OwningProcess
    $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
    $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }
    Write-Host "WARN: Port $preferredStorefrontPort is still occupied by $ownerName. Using $fallbackStorefrontPort." -ForegroundColor Yellow
    $storefrontPort = $fallbackStorefrontPort
}

$selectedPortInUse = Get-NetTCPConnection -LocalPort $storefrontPort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
if ($selectedPortInUse) {
    $ownerPid = $selectedPortInUse.OwningProcess
    $ownerProcess = Get-Process -Id $ownerPid -ErrorAction SilentlyContinue
    $ownerName = if ($ownerProcess) { $ownerProcess.ProcessName } else { "PID $ownerPid" }
    Write-Host "WARN: Candidate storefront port $storefrontPort is occupied by $ownerName. Searching for next available port..." -ForegroundColor Yellow

    $autoStorefrontPort = & "$repoRoot\scripts\find-available-port.ps1" -StartPort $storefrontPort -EndPort 8010 -ReservedPorts @('9000')
    if ($LASTEXITCODE -eq 0 -and $autoStorefrontPort) {
        $storefrontPort = [int]$autoStorefrontPort
        Write-Host "OK: Using auto-discovered storefront port $storefrontPort" -ForegroundColor Green
    } else {
        Write-Host "ERROR: Unable to find an available storefront port in range 8000-8010." -ForegroundColor Red
        pause
        exit 1
    }
}

Write-Host "[2/3] Starting storefront on :$storefrontPort..." -ForegroundColor Yellow
$backendUrl = Resolve-BackendUrl
if (-not $backendUrl) {
    $portsAttempted = if ($runtimeConfig -and $runtimeConfig.BackendPort) { "$($runtimeConfig.BackendPort), 9001, 9002" } else { "9001, 9002" }
    Write-Host "ERROR: No healthy Medusa backend found on ports $portsAttempted." -ForegroundColor Red
    Write-Host "Start backend first with .\\Launch-Admin-Only.bat or .\\Launch-Marketplace.bat" -ForegroundColor Yellow
    pause
    exit 1
}

Write-Host "Using backend URL: $backendUrl" -ForegroundColor Gray
$backendUri = [uri]$backendUrl
$adminPath = if ($runtimeConfig -and $runtimeConfig.AdminPath) { $runtimeConfig.AdminPath } else { "/app" }
Update-LauncherRuntimeConfig -RepoRoot $repoRoot -BackendPort $backendUri.Port -StorefrontPort $storefrontPort -AdminPath $adminPath
Write-Host "Runtime config synced: backend=$($backendUri.Port), storefront=$storefrontPort, adminPath=$adminPath" -ForegroundColor Gray

$storefrontPublishableKey = Resolve-StorefrontPublishableKey
if (-not $storefrontPublishableKey) {
    Write-Host "ERROR: Storefront requires a valid Medusa publishable key." -ForegroundColor Red
    Write-Host "Run: npm run seed" -ForegroundColor Yellow
    pause
    exit 1
}

$storefrontCommand = @"
`$env:MEDUSA_BACKEND_URL='$backendUrl'
`$env:NEXT_PUBLIC_MEDUSA_BACKEND_URL='$backendUrl'
`$env:NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY='$storefrontPublishableKey'
cd `"$storefrontRoot`"
npm run dev -- -p $storefrontPort
"@
$storefrontProcess = Start-Process powershell -ArgumentList '-NoExit', '-Command', $storefrontCommand -PassThru
Write-Host "Storefront process started (PID: $($storefrontProcess.Id))" -ForegroundColor Gray

if (-not (Wait-ForStorefront -Port $storefrontPort)) {
    Write-Host "ERROR: Storefront did not become reachable in time." -ForegroundColor Red
    pause
    exit 1
}

Write-Host "[3/3] Opening storefront..." -ForegroundColor Yellow
$storefrontUrl = "http://localhost:$storefrontPort"
if ($noBrowser) {
    Write-Host "INFO: Browser launch skipped (THERXSPOT_NO_BROWSER=1)." -ForegroundColor Gray
} else {
    Start-Process $storefrontUrl
}

Write-Host ""
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "SUCCESS: Storefront-only environment is ready" -ForegroundColor Green
Write-Host "===================================================" -ForegroundColor Cyan
Write-Host "Storefront URL: $storefrontUrl" -ForegroundColor Yellow
Write-Host ""
